version: '3.9'

services:
  api1:
    build: .
    environment:
      - INSTANCE_ID=api-1
    ports:
      - "8001:8000"

  api2:
    build: .
    environment:
      - INSTANCE_ID=api-2
    ports:
      - "8002:8000"

  api3:
    build: .
    environment:
      - INSTANCE_ID=api-3
    ports:
      - "8003:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - api1
      - api2
      - api3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
